// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootstrap_sums_cpp
Rcpp::NumericMatrix bootstrap_sums_cpp(const Rcpp::NumericMatrix& values, int iterations, double seed, double stream);
RcppExport SEXP _bootabc_bootstrap_sums_cpp(SEXP valuesSEXP, SEXP iterationsSEXP, SEXP seedSEXP, SEXP streamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type stream(streamSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_sums_cpp(values, iterations, seed, stream));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bootabc_bootstrap_sums_cpp", (DL_FUNC) &_bootabc_bootstrap_sums_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bootabc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
