# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_sums_cpp <- function(values, iterations, seed, stream) {
    .Call(`_bootabc_bootstrap_sums_cpp`, values, iterations, seed, stream)
}

